package:
  name: bam-readcount
  version: "1.0.1"

source:
  url: https://github.com/genome/bam-readcount/archive/refs/tags/v1.0.1.tar.gz
  md5: 67f59b210e5ddab97ea57e9fe9a356f6
  sha256: 8ebf84d9efee0f2d3b43f0452dbf16b27337c960e25128f6a7173119e62588b8

build:
  number: 6

requirements:
  build:
    - make
    - cmake >=2.8.3
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - ncurses
    - perl
    - python
  run:
    - python
    - zlib
    - ncurses
    - perl

test:
  commands:
    - bam-readcount 2>&1 | grep bam-readcount > /dev/null

about:
  home: https://github.com/genome/bam-readcount
  license: MIT
  summary: bam-readcount generates metrics at single nucleotide positions.
